---
version: "3.5"
services:
  temporal-ui:
    healthcheck:
      test: ["CMD", "curl", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
  temporal-web:
    healthcheck:
      test: ["CMD", "curl", "--no-verbose", "--tries=1", "--spider", "http://localhost:8088"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
